# Generated by Django 3.2.5 on 2021-08-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_tutorials_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutorials',
            table='Tutorials',
        ),
    ]
