# Generated by Django 3.2.5 on 2021-08-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_alter_tutorials_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorials',
            options={},
        ),
    ]
