# Generated by Django 3.2.5 on 2021-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_alter_tutorials_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('feature_image', models.FileField(upload_to='tutorial/images/')),
                ('attachment', models.FileField(upload_to='tutorial/attachments/')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
